name = input()
print(name + ", " + name + ", " + "bo-b" + name[1:int(len(name))])
print("banana-fana fo-f" + name[1:int(len(name))])
print("fee-fi-mo-m" + name[1:int(len(name))])
print(name[0:int(len(name))] + "!")
